[tool.poetry]
name = "insilico-cancer-center"
version = "0.1.0"
description = "Simulate tumor growth, treatment, and molecular data generation."
license = "MIT"
authors = ["pedrofale <pedro.miguel.ferreira.pf@gmail.com>"]
readme = "README.md"
repository = "https://github.com/pedrofale/iscc"
packages = [{include = "iscc", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
pandas = "^2.2.3"
numpy = ">=1.25,<2.0"
pymuller = "^0.1.2"
click = "^8.0.1"
packcircles = "^0.14"
networkx = "^3.1"
pygraphviz = "^1.11"
tqdm = "^4.57.0"
celluloid = ">=0.2.0"
pyyaml= "^6.0.2"
scikit-learn = "^1.3"
scipy = "^1.11"

[tool.poetry.group.dev.dependencies]
bump2version = "^1.0.1"
black = "^23.7.0"
pytest = "^7.4"

[tool.poetry.group.extra.dependencies]
jupyterlab = "^4.3.4"
squidpy = "^1.6.1"
scanpy = "^1.10.4"

[tool.poetry.scripts]
isccsim = "iscc.tumor.main:main"
isccsample = "iscc.sample.main:main"
isccdata = "iscc.data.main:main"
isccfig = "iscc.visualization.draw:main"
isccgif = "iscc.visualization.animate:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
