"""Tests for the scRNA `estimate_rna()` (DESIGN_inference §B / milestone M2).

Two pillars (cf. the PLOS Comp Bio bar, DESIGN_inference "Why this exists"):
  * **Estimation recovery** — simulate with known ``RNABatchHyperParams`` -> estimate_rna -> recover
    them within tolerance (no external data; the key methods-paper validation).
  * **Runs on realistic data** — estimate_rna on a realistic single-batch AnnData returns valid,
    plausible params.
"""
import numpy as np
import pandas as pd
import pytest

from iscc.data import run_scrna_batches, concat_batches, estimate_rna, scRNA, RNABatchHyperParams


# --------------------------------------------------------------------------------------
# Helpers: build a controlled ground-truth dataset
# --------------------------------------------------------------------------------------
def _cell_data(n_cells, n_genes, seed=0):
    """cell_exp with a per-gene biological profile shared across cells.

    Cell-constant biology isolates the *technical* parameters, so the mean-variance trend
    measures NB dispersion (+ library spread, which `estimate_rna` de-biases) rather than biological
    cell-cell variation. Real data has both; recovery needs the controlled case.
    """
    rng = np.random.default_rng(seed)
    genes = [f"g{i}" for i in range(n_genes)]
    profile = rng.lognormal(0.0, 1.0, size=n_genes)
    exp = pd.DataFrame(np.tile(profile, (n_cells, 1)),
                       index=[f"C{i}" for i in range(n_cells)], columns=genes)
    return {"cell_exp": exp}


def _multibatch_adata(truth, n_batches=16, n_cells=400, n_genes=300, base_seed=7):
    cell_data = _cell_data(n_cells, n_genes)
    assays = run_scrna_batches(cell_data, n_batches=n_batches, base_seed=base_seed,
                               design="shared", protocol="10x", n_cells=n_cells, **truth)
    adata = concat_batches(assays)
    adata.obs["batch"] = adata.obs["batch"].astype(str)
    realized_depth_sd = float(np.std(np.log([a.batch.mu_lib_b for a in assays])))
    return adata, realized_depth_sd


# --------------------------------------------------------------------------------------
# Estimation recovery (the headline methods-paper test)
# --------------------------------------------------------------------------------------
class TestRecovery:
    TRUTH = dict(sigma_batch=0.30, mu_lib=3000.0, sigma_lib=0.40, dispersion=0.25,
                 depth_batch_sigma=0.20, ambient_frac=0.0, doublet_rate=0.0,
                 dropout_mid=0.0, well_sigma=0.0)

    @pytest.fixture(scope="class")
    def fit(self):
        adata, realized_depth_sd = _multibatch_adata(self.TRUTH)
        est = estimate_rna(adata, protocol="10x", batch_key="batch")
        return est, realized_depth_sd

    def test_library_size_recovered(self, fit):
        est, _ = fit
        assert est.hypers.mu_lib == pytest.approx(self.TRUTH["mu_lib"], rel=0.05)
        assert est.hypers.sigma_lib == pytest.approx(self.TRUTH["sigma_lib"], abs=0.05)

    def test_dispersion_recovered(self, fit):
        """Library-de-biased NB dispersion lands near truth (raw mean-var trend would inflate)."""
        est, _ = fit
        assert est.hypers.dispersion == pytest.approx(self.TRUTH["dispersion"], abs=0.06)

    def test_sigma_batch_recovered(self, fit):
        """Per-gene cross-batch log-fold-change scale (needs >=2 batches)."""
        est, _ = fit
        assert est.n_batches >= 2
        assert "sigma_batch" in est.fitted
        assert est.hypers.sigma_batch == pytest.approx(self.TRUTH["sigma_batch"], abs=0.06)

    def test_depth_batch_sigma_tracks_realized_spread(self, fit):
        """`estimate_rna` sees only the *realized* per-batch depths; it recovers their spread.

        The gap from the realized spread to the 0.20 hyper-parameter is genuine finite-batch
        sampling (a LogNormal sd from ~16 draws), not estimator bias — so the honest target is
        the realized spread, which it matches tightly.
        """
        est, realized_depth_sd = fit
        assert est.hypers.depth_batch_sigma == pytest.approx(realized_depth_sd, abs=0.04)
        assert 0.05 < est.hypers.depth_batch_sigma < 0.35   # right ballpark of truth (0.20)

    def test_ambient_and_doublet_are_priors_not_claimed_fit(self, fit):
        """Counts-only data cannot identify ambient/doublet rates -> carried from preset."""
        est, _ = fit
        assert "ambient_frac" not in est.fitted
        assert "doublet_rate" not in est.fitted
        assert est.hypers.ambient_frac == pytest.approx(0.05)   # 10x preset


# --------------------------------------------------------------------------------------
# Runs on realistic data + returns valid params
# --------------------------------------------------------------------------------------
class TestRunsOnRealisticData:
    def _realistic_adata(self, protocol, seed=1):
        # one batch generated by the assay itself with the protocol preset = realistic counts
        cell_data = _cell_data(n_cells=500, n_genes=400, seed=2)
        a = scRNA(protocol=protocol, n_cells=500, seed=seed).run(cell_data)
        return a.to_anndata()

    def test_estimate_returns_valid_params_10x(self):
        adata = self._realistic_adata("10x")
        est = estimate_rna(adata, protocol="10x")
        h = est.hypers
        assert h.mu_lib > 0 and h.sigma_lib > 0
        assert h.dispersion >= 0
        assert np.isfinite(h.dropout_mid) and h.dropout_mid >= 0
        # single batch -> batch params not fit, fall back to preset
        assert est.n_batches == 1
        assert "sigma_batch" not in est.fitted
        assert est.gene_means.shape == (adata.n_vars,)

    def test_protocol_aware_smartseq3_disables_dropout(self):
        adata = self._realistic_adata("smartseq3")
        est = estimate_rna(adata, protocol="smartseq3")
        assert est.protocol == "smartseq3"
        assert est.hypers.dropout_mid == 0.0          # dropout off for plate / 5'-UMI
        assert "dropout_mid" not in est.fitted
        assert est.hypers.well_sigma > 0              # well-in-plate nesting kept active

    def test_smartseq3_estimate_keeps_the_whole_plate_layout(self):
        """A count matrix carries no plate map, so the layout is carried from the preset — but it
        must be carried, not dropped: a fitted Smart-seq3 estimate that reports ``n_wells=0`` has
        silently turned itself into a plate-less protocol."""
        est = estimate_rna(self._realistic_adata("smartseq3"), protocol="smartseq3")
        assert est.hypers.n_wells == 384              # 384-well plates, not "no plates"
        assert est.hypers.n_plates == 0               # as many as the cells need
        assert est.hypers.plate_sigma == 0.0          # preset default: layout is bookkeeping only
        # ... and it says so, instead of implying the layout was measured
        assert {"n_wells", "n_plates", "plate_sigma", "well_sigma"} <= set(est.carried)
        assert not set(est.carried) & set(est.fitted)

        a = scRNA(n_cells=50, **est.scrna_kwargs()).run(_cell_data(80, 400, seed=5))
        assert a.plates is not None and a.plates.n_wells == 384

    def test_droplet_estimate_has_no_plate_layer(self):
        est = estimate_rna(self._realistic_adata("10x"), protocol="10x")
        assert est.hypers.n_wells == 0 and est.hypers.plate_sigma == 0.0
        assert est.hypers.well_sigma == 0.0
        assert scRNA(n_cells=50, **est.scrna_kwargs()).run(
            _cell_data(80, 400, seed=6)).plates is None

    def test_single_batch_cross_batch_terms_are_reported_as_carried(self):
        est = estimate_rna(self._realistic_adata("10x"), protocol="10x")
        assert est.n_batches == 1
        assert {"sigma_batch", "depth_batch_sigma"} <= set(est.carried)
        assert {"mu_lib", "sigma_lib", "dispersion"} <= set(est.fitted)

    def test_dropout_fit_can_be_forced_off(self):
        adata = self._realistic_adata("10x")
        est = estimate_rna(adata, protocol="10x", fit_dropout=False)
        assert est.hypers.dropout_mid == 0.0

    def test_scrna_kwargs_drive_the_assay(self):
        """Fitted params splat straight back into scRNA without redefinition."""
        adata = self._realistic_adata("10x")
        est = estimate_rna(adata, protocol="10x")
        kwargs = est.scrna_kwargs()
        assert "kappa" not in kwargs                  # set via count_model, not a constructor knob
        a = scRNA(n_cells=50, **kwargs).run(_cell_data(80, 400, seed=3))
        assert a.observed_counts.shape == (50, 400)

    def test_accepts_dataframe_and_ndarray(self):
        cell_data = _cell_data(120, 200, seed=4)
        a = scRNA(protocol="10x", n_cells=120, seed=0).run(cell_data)
        df = a.observed_counts
        est_df = estimate_rna(df, protocol="10x")
        est_np = estimate_rna(df.values, protocol="10x")
        assert est_df.hypers.mu_lib == pytest.approx(est_np.hypers.mu_lib, rel=1e-9)

    def test_unknown_protocol_raises(self):
        with pytest.raises(ValueError):
            estimate_rna(np.ones((10, 5)), protocol="nanopore")
